export const fallbackContent = {
  de: {
    navSociety: "Gesellschaft",
    navPhilosophy: "Philosophie",
    navMembership: "Mitgliedschaft",
    navAdminPages: "Admin Inhalte",

    heroTag: "Eine private Fahrergesellschaft",
    heroTitle: "Automobile Kultur,\nstill verstanden.",
    heroText:
      "The Heritage Drivers ist ein erlesener Kreis für jene, die Kultur, Handwerkskunst und die zeitlose Präsenz aussergewöhnlicher Automobile zu schätzen wissen.",
    cta1: "Anfrage stellen",
    cta2: "Mehr erfahren",

    tag1: "Automobile",
    tag2: "Kultur",
    tag3: "Handwerk",
    tag4: "Stil",

    philosophyTitle: "Nicht jedes Automobil bedarf einer Erklärung.",
    membershipTitle: "Zugang ist bewusst gewählt – nicht breit verteilt.",
    membershipText:
      "Mitgliedsanfragen können diskret eingereicht werden. Die Gesellschaft ist selektiv, persönlich und basiert auf gemeinsamen Werten wie Stil, Haltung und technischem Verständnis.",

    enquiryName: "Name",
    enquiryEmail: "E-Mail",
    enquiryMessage: "Kurze Beschreibung Ihres Interesses",
    enquirySubmit: "Anfrage senden",

    loginButton: "Mitglieder-Login",
    loginTitle: "Mitgliederbereich",
    loginSubtitle:
      "Ausschliesslich für registrierte Mitglieder der Gesellschaft.",
    loginFullName: "Vollständiger Name",
    loginEmail: "E-Mail-Adresse",
    loginPassword: "Passwort",
    loginSubmit: "Anmelden",
    signupSubmit: "Konto erstellen",
    loginClose: "Schliessen",
    switchToLogin: "Bereits registriert? Anmelden",
    switchToSignup: "Neues Mitglied? Zugang erstellen",
    loginForgot: "Passwort-Reset kann später über Supabase ergänzt werden.",
    loginNote: "Zugang nur für berechtigte Mitglieder.",

    secureAccess: "Geschützter Zugang",
    welcome: "Willkommen zurück",
    membersIntro:
      "Ihr Konto ist über Supabase-Authentifizierung geschützt. Mitgliederdaten, Events und geschützte Inhalte können sicher gepflegt werden.",

    eventCardTitle: "Nächste Ausfahrt",
    eventCardText:
      "Season Opening · 19.04.2026 · Teilnahme nur nach Bestätigung.",
    notesTitle: "Mitteilungen",
    notesText:
      "Diskrete Updates, Club-Hinweise und Korrespondenz der Gesellschaft.",
    atelierTitle: "Technischer Zirkel",
    atelierText:
      "Ausgewählte Werkstattabende, Heritage-Gespräche und mechanischer Austausch.",

    approvalPendingTitle: "Mitgliedschaft in Prüfung",
    approvalPendingText:
      "Ihr Konto wurde erfolgreich erstellt. Der Zugang zum privaten Mitgliederbereich wird nach Prüfung und Freigabe Ihrer Mitgliedschaft manuell erteilt.",

    eventsSectionTitle: "Anstehende Events & Teilnahme",
    eventsSectionText:
      "Verwalten Sie Ausfahrten, prüfen Sie Anmeldungen und pflegen Sie die Event-Daten der Gesellschaft.",
    eventLoading: "Events werden geladen...",
    eventEmpty: "Noch keine Events vorhanden.",
    eventAttend: "An diesem Event teilnehmen",
    eventParticipants: "Teilnehmer",
    eventClose: "Schliessen",
    eventModify: "Event bearbeiten",
    eventCreate: "Event erstellen",
    eventPropose: "Event vorschlagen",
    eventCancelEdit: "Bearbeitung abbrechen",
    eventTitleLabel: "Event-Titel",
    eventDateLabel: "Event-Datum",
    eventLocationLabel: "Ort",
    eventMaxParticipantsLabel: "Max. Teilnehmer",
    eventShortDescriptionLabel: "Kurzbeschreibung",
    eventLongDescriptionLabel: "Ausführliche Beschreibung",
    eventImageLabel: "Event-Bild",
    eventAttachmentLabel: "Event-Dateien / Roadbook",
    eventSaveChanges: "Änderungen speichern",
    eventNoParticipants: "Noch keine Teilnehmer angemeldet.",
    eventUpcoming: "Anstehendes Event",
    eventOpenAttachment: "Anhang öffnen",
    eventDelete: "Event löschen",
    eventArchive: "Event archivieren",
    eventApprove: "Event freigeben",
    eventPromote: "Event bewerben",
    eventPending: "Wartet auf Freigabe",
    eventApproved: "Freigegeben",
    eventFiles: "Dateien / Roadbook",

    accountTitle: "Kontoeinstellungen",
    accountSubtitle:
      "Pflegen Sie Ihre Mitgliederdaten und Zugangsinformationen.",
    accountDisplayName: "Anzeigename",
    accountEmail: "E-Mail-Adresse",
    accountNewPassword: "Neues Passwort",
    accountConfirmPassword: "Neues Passwort bestätigen",
    accountSaveName: "Name speichern",
    accountSaveEmail: "E-Mail speichern",
    accountSavePassword: "Passwort speichern",

    adminTitle: "Admin Panel",
    adminSubtitle: "Anfragen prüfen und registrierte Benutzer freigeben.",
    adminEnquiries: "Mitgliedsanfragen",
    adminMembers: "Registrierte Mitglieder",
    adminNoEnquiries: "Keine Anfragen vorhanden.",
    adminNoMembers: "Keine Mitglieder gefunden.",
    adminApprove: "Mitglied freigeben",
    adminMarkReviewed: "Als geprüft markieren",
    adminApproved: "Freigegeben",
    adminPending: "Ausstehend",
    adminReviewed: "Geprüft",
    adminNew: "Neu",
    adminSaveRole: "Rolle speichern",
    adminRole: "Rolle",
    adminCreateProfile: "Profil erstellen",
    adminMissingProfile: "Noch kein Mitgliederprofil",

    footerImprintTitle: "Impressum",
    footerImprintText: "Rechtliche Hinweise und Kontaktangaben.",
    footerAffiliationTitle: "Zugehörigkeit",
    footerAffiliationText:
      "The Heritage Drivers ist eine private Fahrergesellschaft.",
    footerSponsorsTitle: "Sponsoren",
    footerSponsorsText: "Ausgewählte Partner und unterstützende Häuser.",
    footerBottomLine: "The Heritage Drivers",
    footerImprintLink: "Zum Impressum",

    modify: "Ändern",
    save: "Speichern",
    cancel: "Abbrechen",
  },

  en: {
    navSociety: "Society",
    navPhilosophy: "Philosophy",
    navMembership: "Membership",
    navAdminPages: "Admin Pages",

    heroTag: "A Private Drivers Society",
    heroTitle: "Heritage motoring,\nquietly understood.",
    heroText:
      "The Heritage Drivers is a refined circle for those who appreciate the culture, craftsmanship and enduring presence of distinguished motor cars.",
    cta1: "Request Access",
    cta2: "Discover More",

    tag1: "Motor Cars",
    tag2: "Culture",
    tag3: "Craftsmanship",
    tag4: "Taste",

    philosophyTitle: "Not every motor car needs explanation.",
    membershipTitle: "Admission is intended to be considered, not crowded.",
    membershipText:
      "Membership enquiries may be submitted discreetly. The society is envisioned as selective, personal and founded on shared standards of taste, conduct and mechanical appreciation.",

    enquiryName: "Name",
    enquiryEmail: "Email",
    enquiryMessage: "A brief note about your interest",
    enquirySubmit: "Submit Enquiry",

    loginButton: "Member Login",
    loginTitle: "Members Access",
    loginSubtitle: "Reserved for registered members of the society.",
    loginFullName: "Full name",
    loginEmail: "Email address",
    loginPassword: "Password",
    loginSubmit: "Sign In",
    signupSubmit: "Create Account",
    loginClose: "Close",
    switchToLogin: "Already registered? Sign in",
    switchToSignup: "New member? Create access",
    loginForgot: "Password reset can be added via Supabase if desired.",
    loginNote: "Private access only.",

    secureAccess: "Protected access",
    welcome: "Welcome back",
    membersIntro:
      "Your account is protected by Supabase authentication. Member data, events and protected content can be maintained securely.",

    eventCardTitle: "Upcoming Drive",
    eventCardText:
      "Season Opening · 19.04.2026 · Private confirmation required.",
    notesTitle: "Members Notes",
    notesText: "Discreet updates, club notices and society correspondence.",
    atelierTitle: "Technical Circle",
    atelierText:
      "Selected workshop evenings, heritage discussions and mechanical exchange.",

    approvalPendingTitle: "Membership Awaiting Approval",
    approvalPendingText:
      "Your account has been created successfully. Access to the private members area is granted manually once your membership has been reviewed and approved.",

    eventsSectionTitle: "Upcoming Events & Attendance",
    eventsSectionText:
      "Manage upcoming drives, review attendance and maintain event details for the society.",
    eventLoading: "Loading events...",
    eventEmpty: "No events available yet.",
    eventAttend: "Attend this event",
    eventParticipants: "Participants",
    eventClose: "Close",
    eventModify: "Modify Event",
    eventCreate: "Create Event",
    eventPropose: "Propose Event",
    eventCancelEdit: "Cancel Edit",
    eventTitleLabel: "Event title",
    eventDateLabel: "Event date",
    eventLocationLabel: "Location",
    eventMaxParticipantsLabel: "Max participants",
    eventShortDescriptionLabel: "Short description",
    eventLongDescriptionLabel: "Detailed description",
    eventImageLabel: "Event image",
    eventAttachmentLabel: "Event files / roadbook",
    eventSaveChanges: "Save Changes",
    eventNoParticipants: "No participants registered yet.",
    eventUpcoming: "Upcoming Event",
    eventOpenAttachment: "Open attachment",
    eventDelete: "Delete Event",
    eventArchive: "Archive Event",
    eventApprove: "Approve Event",
    eventPromote: "Promote Event",
    eventPending: "Pending approval",
    eventApproved: "Approved",
    eventFiles: "Files / Roadbook",

    accountTitle: "Account Settings",
    accountSubtitle: "Maintain your member details and access credentials.",
    accountDisplayName: "Display name",
    accountEmail: "Email address",
    accountNewPassword: "New password",
    accountConfirmPassword: "Confirm new password",
    accountSaveName: "Save Name",
    accountSaveEmail: "Save Email",
    accountSavePassword: "Save Password",

    adminTitle: "Admin Panel",
    adminSubtitle: "Review enquiries and approve registered members.",
    adminEnquiries: "Membership Enquiries",
    adminMembers: "Registered Members",
    adminNoEnquiries: "No enquiries available.",
    adminNoMembers: "No members found.",
    adminApprove: "Approve Member",
    adminMarkReviewed: "Mark Reviewed",
    adminApproved: "Approved",
    adminPending: "Pending",
    adminReviewed: "Reviewed",
    adminNew: "New",
    adminSaveRole: "Save Role",
    adminRole: "Role",
    adminCreateProfile: "Create Profile",
    adminMissingProfile: "No member profile yet",

    footerImprintTitle: "Imprint",
    footerImprintText: "Legal notice and contact details.",
    footerAffiliationTitle: "Affiliation",
    footerAffiliationText:
      "The Heritage Drivers is a private motoring society.",
    footerSponsorsTitle: "Sponsors",
    footerSponsorsText: "Selected partners and supporting houses.",
    footerBottomLine: "The Heritage Drivers",
    footerImprintLink: "View imprint",

    modify: "Modify",
    save: "Save",
    cancel: "Cancel",
  },
};

export const uiMessages = {
  de: {
    loginSuccess: "Anmeldung erfolgreich.",
    signupSuccess:
      "Konto erstellt. Bitte bestätigen Sie Ihre Registrierung über die E-Mail.",
    logoutSuccess: "Sie wurden abgemeldet.",
    genericError:
      "Etwas ist schiefgelaufen. Bitte prüfen Sie die Konfiguration und versuchen Sie es erneut.",
    notAuthorized: "Keine Berechtigung für diese Aktion.",
    eventCreateError: "Event konnte nicht gespeichert werden.",
    eventCreateSuccess: "Event erfolgreich erstellt.",
    eventProposalSuccess:
      "Event-Vorschlag eingereicht. Er wird nach Admin-Freigabe sichtbar.",
    eventUpdateSuccess: "Event erfolgreich aktualisiert.",
    eventDeleteSuccess: "Event erfolgreich gelöscht.",
    eventArchiveSuccess: "Event erfolgreich archiviert.",
    eventApproveSuccess: "Event erfolgreich freigegeben.",
    eventPromoteSuccess: "Event wurde an die Mitglieder versendet.",
    eventPromoteError: "Event konnte nicht beworben werden.",
    eventDeleteConfirm: "Soll dieses Event wirklich gelöscht werden?",
    eventArchiveConfirm: "Soll dieses Event wirklich archiviert werden?",
    profileUpdateSuccess: "Anzeigename erfolgreich aktualisiert.",
    emailUpdateSuccess:
      "Änderung der E-Mail angestossen. Bitte die Bestätigungs-E-Mail von Supabase prüfen.",
    passwordUpdateSuccess: "Passwort erfolgreich aktualisiert.",
    passwordMismatch: "Die neuen Passwörter stimmen nicht überein.",
    passwordTooShort:
      "Bitte verwenden Sie ein Passwort mit mindestens 8 Zeichen.",
    participantUpdateSuccess: "Teilnahme erfolgreich aktualisiert.",
    uploadError: "Datei-Upload fehlgeschlagen.",
    enquirySuccess: "Ihre Anfrage wurde erfolgreich übermittelt.",
    enquiryError: "Ihre Anfrage konnte nicht übermittelt werden.",
    enquiryMissingFields:
      "Bitte geben Sie mindestens Ihren Namen und Ihre E-Mail-Adresse an.",
    setupTitle: "Supabase-Einrichtung erforderlich",
    setupText:
      "Ersetzen Sie die Platzhalter für Supabase URL und Anon Key.",
    approvalSuccess: "Mitglied erfolgreich freigegeben.",
    enquiryReviewedSuccess: "Anfrage als geprüft markiert.",
    roleUpdateSuccess: "Mitgliedsrolle erfolgreich aktualisiert.",
    contentUpdateSuccess: "Inhalt erfolgreich aktualisiert.",
    createProfileSuccess: "Profil erfolgreich erstellt.",
  },

  en: {
    loginSuccess: "Login successful.",
    signupSuccess:
      "Account created. Please check your email to confirm your registration.",
    logoutSuccess: "You have been signed out.",
    genericError:
      "Something went wrong. Please review the configuration and try again.",
    notAuthorized: "Not authorized to perform this action.",
    eventCreateError: "Could not save event.",
    eventCreateSuccess: "Event created successfully.",
    eventProposalSuccess:
      "Event proposal submitted. It will be visible after admin approval.",
    eventUpdateSuccess: "Event updated successfully.",
    eventDeleteSuccess: "Event deleted successfully.",
    eventArchiveSuccess: "Event archived successfully.",
    eventApproveSuccess: "Event approved successfully.",
    eventPromoteSuccess: "Event was sent to members.",
    eventPromoteError: "Event could not be promoted.",
    eventDeleteConfirm: "Do you really want to delete this event?",
    eventArchiveConfirm: "Do you really want to archive this event?",
    profileUpdateSuccess: "Profile name updated successfully.",
    emailUpdateSuccess:
      "Email update requested. Please confirm via the email sent by Supabase.",
    passwordUpdateSuccess: "Password updated successfully.",
    passwordMismatch: "The new passwords do not match.",
    passwordTooShort: "Please use a password with at least 8 characters.",
    participantUpdateSuccess: "Attendance updated successfully.",
    uploadError: "File upload failed.",
    enquirySuccess: "Your enquiry has been submitted successfully.",
    enquiryError: "Your enquiry could not be submitted.",
    enquiryMissingFields:
      "Please provide at least your name and email address.",
    setupTitle: "Supabase setup required",
    setupText:
      "Replace the placeholder Supabase URL and anon key in the code.",
    approvalSuccess: "Member approved successfully.",
    enquiryReviewedSuccess: "Enquiry marked as reviewed.",
    roleUpdateSuccess: "Member role updated successfully.",
    contentUpdateSuccess: "Content updated successfully.",
    createProfileSuccess: "Profile created successfully.",
  },
};